version: "3.8"

services:
  app:
    container_name: netflix-dev
    image: netflix-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/netflix/src
    ports:
      - 3000:3000
